version: "3.3"
services:
  localstack:
    container_name: "localstack_trips"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - DEBUG=0
      - SERVICES=dynamodb
      - LOCALSTACK_HOSTNAME=localhost
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=whatever
      - AWS_SECRET_ACCESS_KEY=whatever
      - AWS_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"